# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: ubuntu-latest

jobs:
- job: Development_Run
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g @angular/cli
      npm install
      ng build
      ls
    displayName: 'npm install and build'

  - task: CmdLine@2
    inputs:
      script: |
        ls
        cd /home/vsts/work/1/s
        ls
        npm install -g firebase-tools
        firebase deploy --token $(FIREBASE_TOKEN) --project $(FIREBASE_PROJECT_DEV) --only hosting:$(FIREBASE_HOSTING_DEV) --force -m "$(Build.BuildNumber)"
    displayName: 'firebase publish -m "$(Build.BuildNumber)"'

- job: Production_Run
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g @angular/cli
      npm install
      ng build --prod
      ls
    displayName: 'npm install and build'

  - task: CmdLine@2
    inputs:
      script: |
        ls
        cd /home/vsts/work/1/s
        ls
        npm install -g firebase-tools
        firebase deploy --token $(FIREBASE_TOKEN) --project $(FIREBASE_PROJECT) --only hosting:$(FIREBASE_HOSTING) --force -m "$(Build.BuildNumber)"
    displayName: 'firebase publish -m "$(Build.BuildNumber)"'
